services:
  - type: web
    name: neutral-news-backend
    runtime: node
    plan: free
    buildCommand: chmod +x build-for-render.sh && ./build-for-render.sh
    startCommand: cd /opt/render/project && pwd && ls -la && echo "Checking build folder:" && ls -la build/ && echo "Checking dist folder:" && ls -la dist/ && echo "Checking src/dist folder:" && ls -la src/dist/ && echo "Starting app from build/index.js..." && node build/index.js
    envVars:
      - key: NODE_ENV
        value: production
