services:
  - type: web
    name: neutral-news-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node start-app.js
    envVars:
      - key: NODE_ENV
        value: production
