services:
  - type: web
    name: neutral-news-backend
    runtime: node
    plan: free
    buildCommand: cd /opt/render/project && npm install && npm run build
    startCommand: cd /opt/render/project && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
